services:
  openldap-node1:
    image: openldap-custom:latest
    container_name: openldap-oiocloud-node1
    hostname: openldap-oiocloud-node1
    env_file:
      - .env.node1
    ports:
      - "392:389"
      - "639:636"
    volumes:
      - ldap-data-node1:/var/lib/ldap
      - ldap-config-node1:/etc/openldap/slapd.d
      - ./logs/node1:/logs
      - ./custom-schema:/custom-schema:ro
      - ./sample/oiocloud_data.ldif:/data/oiocloud_data.ldif:ro
      - ./init/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh:ro
    restart: unless-stopped
    networks:
      - ldap-shared-network

  openldap-node2:
    image: openldap-custom:latest
    container_name: openldap-oiocloud-node2
    hostname: openldap-oiocloud-node2
    env_file:
      - .env.node2
    ports:
      - "393:389"
      - "640:636"
    volumes:
      - ldap-data-node2:/var/lib/ldap
      - ldap-config-node2:/etc/openldap/slapd.d
      - ./logs/node2:/logs
      - ./custom-schema:/custom-schema:ro
    restart: unless-stopped
    networks:
      - ldap-shared-network
    depends_on:
      - openldap-node1

  openldap-node3:
    image: openldap-custom:latest
    container_name: openldap-oiocloud-node3
    hostname: openldap-oiocloud-node3
    env_file:
      - .env.node3
    ports:
      - "394:389"
      - "641:636"
    volumes:
      - ldap-data-node3:/var/lib/ldap
      - ldap-config-node3:/etc/openldap/slapd.d
      - ./logs/node3:/logs
      - ./custom-schema:/custom-schema:ro
    restart: unless-stopped
    networks:
      - ldap-shared-network
    depends_on:
      - openldap-node1

volumes:
  ldap-data-node1:
  ldap-config-node1:
  ldap-data-node2:
  ldap-config-node2:
  ldap-data-node3:
  ldap-config-node3:

networks:
  ldap-shared-network:
    external: true
